config/routes.rb
Rails.application.routes.draw do
  resources 'homes',only: [:index]
    root 'homes#index'
  namespace :homes do
    get 'products/cart'
    get 'products/order_build'
    resources 'products'
  end
  
  resources 'backends',only: [:index]
  namespace :backends do
    root to: 'backends#index'
    resource :sessions , only: [:create,:destroy]
    resources :systems,only: %w(edit update)
    resources :admins do
      collection do
        get :login
      end
    end
    resources :products
    resources :contents
    resources :categories
    resources :orders
    resources :attachments do
      collection do
        post :sort
        post :ck_upload
        delete :delete
      end
    end
    resources :navs do
      collection do
        post :sort
      end
    end
    post 'carts/add_session'
    post 'carts/delete_session'
  end
end

app/models/nav.rb
class Nav < ActiveRecord::Base
  scope :mark,-> {where(del_mark: false).order('rank')}
  scope :main,-> {where(parent_id: nil)}

  acts_as_nested_set

  enum nav_type: %w(header footer)
  def parent
    parent = Nav.find(self.parent_id)
    return parent
  end
end

app/controllers/backends/admins_controller.rb
class Backends::AdminsController < BackendsController
  skip_before_action :check_login,only: [:login]
  def login
    @system = System.first
    render layout: false
  end

  def edit
    render layout: false
  end

  def update
    @admin = Admin.find(params[:id])

    @admin.update(admin_params_permit)

    redirect_to :back,flash: { success: '更新成功'}
  end

  private

  def admin_params_permit
    params.require(:admin).permit(:name, :account, :password)
  end

end

app/controllers/backends/attachments_controller.rb
class Backends::AttachmentsController < BackendsController
 skip_before_filter :verify_authenticity_token

  before_action :find_attachment

  def new
    render layout: false,template: "backends/attachments/_form"
  end

  def create
    @attachment = Attachment.new
    @attachment.file = params[:file]
    @attachment.save

    render json: @attachment.to_json
  end

  def sort
    @attachments = Attachment.mark.where(id: params[:sort])

    @attachments.each do |a|
      a.update(rank: params[:sort].index(a.id.to_s))
    end

    render json: 'sort_success'
  end

  def update
    @attachment.update(file: params[:file])

    render json: @attachment.to_json
  end

  def delete
    @attachment.update(del_mark: true)
    render json: @attachment.to_json
  end

  def ck_upload
    @attachment = Attachment.create(file: params[:upload],del_mark: true)

    # render :text=>u.obj_tmp.url
    render  :text=> "<script>window.parent.CKEDITOR.tools.callFunction(#{params[:CKEditorFuncNum]},\"#{@attachment.file.url}\")</script>"
    return
  end

  private

  def find_attachment
    @attachment = Attachment.find_by(id: params[:id]) ? Attachment.find_by(id: params[:id]) : Attachment.new
  end

  def attachment_params_permit
    params.require(:attachment).permit(:file,:attachmenttable_type, :attachmenttable_id)

  end
end

app/controllers/backends/carts_controller.rb
class Backends::CartsController < BackendsController
	skip_before_filter :verify_authenticity_token
	skip_before_action :check_login


	def add_session
		if session[:cart_id].blank?
			session[:cart_id] = Hash.new
		end
			session[:cart_id]["cart"+params[:id]] = params[:id]
			render json: session
	end
	
	def delete_session
		session[:cart_id].delete("cart#{params[:id]}")
		
		render text: 'delete'
	end
end

app/controllers/backends/categories_controller.rb
class Backends::CategoriesController < BackendsController

  before_action :find_category,except: [:index]

  skip_before_filter :verify_authenticity_token,only: [:sort]

  def index
    @categories = Category.mark
  end

  def new
    render layout: false
  end

  def create
    @category.update(category_params_permit)

    redirect_to :back,flash: { success: '新增成功'}
  end

  def edit
    render layout: false
  end

  def sort
    @categories = Category.mark.where(id: params[:sort])

    @categories.each do |c|
      c.update(rank: params[:sort].index(c.id.to_s))
    end

    render json: 'sort_success'
  end

  def update
    @category.update(category_params_permit)

    redirect_to :back,flash: { success: '更新成功'}
  end

  def destroy
    @category.update(del_mark: true)

    redirect_to :back,flash: { success: '刪除成功'}
  end

  private

  def category_params_permit
    params.require(:category).permit(:name, :category_type)
  end

  def find_category
    @category = Category.find_by(id: params[:id]) ? Category.find_by(id: params[:id]) : Category.new
  end

end

app/controllers/backends/contents_controller.rb
class Backends::ContentsController < BackendsController
  before_action :find_content,except:  [:index]
  before_action :find_categories
  def index
    if Content.content_types.keys.include?(params[:type])
      @contents = Content.mark.send(params[:type])
    else
      @contents = Content.mark
    end
  end

  def new
    @content.content_type = params[:type]
    @content.build_attachment
    @attachments = @content.attachments
  end

  def create
    @content.update(content_params_permit)
    update_attachment

    redirect_to backends_contents_path(type: @content.content_type) ,flash: { success: '新增成功'}
  end

  def edit
    @content.build_attachment
  end

  def update
    @content.update(content_params_permit)
    update_attachment

    redirect_to :back,flash: { success: '更新成功'}
  end

  def destroy
    @content.update(del_mark: true)

    redirect_to :back,flash: { success: '刪除成功'}
  end

  private

  def content_params_permit
    params.require(:content).permit(:title, :content, :category_id,:content_type,:intro)
  end

  def update_attachment
    @attachments = Attachment.where(id: params[:attachment][:id])
    @attachments.update_all(attachmenttable_type: @content.class.name,attachmenttable_id: @content.id)
  end

  def find_content
    @content = Content.find_by(id: params[:id]) ? Content.find_by(id: params[:id]) : Content.new
  end

  def find_categories
    @categories = Category.mark
  end
end

app/controllers/backends/navs_controller.rb
class Backends::NavsController < BackendsController

  before_action :find_nav,except: :index

  skip_before_filter :verify_authenticity_token,only: :sort

  def index
    if Nav.nav_types.keys.include?(params[:type])
      @navs = Nav.mark.send(params[:type])
    else
      @navs = Nav.mark
    end

    @navs = @navs.where(parent_id: params[:parent_id])

  end


  def new

    render layout: false
  end

  def create
    @nav.update(nav_params_permit)

    redirect_to :back,flash: {success: "Create Success!"}
  end

  def edit
    render layout: false
  end

  def sort
    @navs = Nav.mark.where(id: params[:sort])

    @navs.each do |n|
      n.update(rank: params[:sort].index(n.id.to_s))
    end

    render json: 'sort_success'
  end


  def update
    @nav.update(nav_params_permit)

    redirect_to :back,flash: {success: "Update Success!"}
  end

  def destroy
    @nav.update(del_mark: true)

    redirect_to :back,flash: {success: "Delete Success!"}
  end

  private

  def find_nav
    @nav = params[:id] ? Nav.find_by(id: params[:id]) : Nav.new
  end

  def nav_params_permit
    params.require(:nav).permit(:url,:nav_type,:parent_id,:name)
  end
end

app/controllers/backends/orders_controller.rb
class Backends::OrdersController < BackendsController
	skip_before_action :check_login
	def create
		@order = Order.create(order_params)
		@order.trace_fb_id = session[:from_fb] if session[:from_fb].present?
		@sum = 0
		@order.product_id.each_with_index do |product,index|
			@product = Product.find(product)
			@sum += @product.price.to_i * @order.count[index].to_i
		end
		@order.price = @sum
		@order.save
		session[:cart_id]=nil
		redirect_to homes_products_order_build_path(id: @order.id),flash: { success: '預購成功'}
	end

	def index
		headers['Content-Type'] = "application/vnd.ms-excel"
		headers['Content-Disposition'] = 'attachment; filename="list.xls" '
		headers['Cache-Control'] = ''
		@orders = Order.all
		render layout: false
	end
	private
	def order_params
		params.require(:order).permit(:name,:fb_name,:study_at,:phone,product_id: [],count: [])
	end
end

app/controllers/backends/products_controller.rb
class Backends::ProductsController < BackendsController
  before_action :find_product,except:  [:index]
  def index
      @products = Product.all
  end

  def new
    @product.build_attachment
    @attachments = @product.attachments
  end

  def create
    @product.update(product_params_permit)
    update_attachment

    redirect_to backends_products_path,flash: { success: '新增成功'}
  end

  def edit
    @product.build_attachment
  end

  def update
    @product.update(product_params_permit)
    update_attachment

    redirect_to :back,flash: { success: '更新成功'}
  end

  def destroy
    @product.update(del_mark: true)

    redirect_to :back,flash: { success: '刪除成功'}
  end

  private

  def product_params_permit
    params.require(:product).permit(:name, :price,:intro,:category_id)
  end

  def update_attachment
    @attachments = Attachment.where(id: params[:attachment][:id])
    @attachments.update_all(attachmenttable_type: @product.class.name,attachmenttable_id: @product.id)
  end

  def find_product
    @product = Product.find_by(id: params[:id]) ? Product.find_by(id: params[:id]) : Product.new
  end

end

app/controllers/backends/sessions_controller.rb
class Backends::SessionsController <  BackendsController
  skip_before_action :check_login
  def create
    @admin = Admin.find_by(account: params[:account])
    if @admin && @admin.authenticate(params[:password])
      session[:admin_id] = @admin.id
      redirect_to backends_path ,flash: { success: '登入成功'}
    else
      redirect_to :back,flash: { error: '登入失敗'}
    end
  end

  def destroy
    session.delete(:admin_id)
    redirect_to backends_path,flash: { success: '登出成功'}
  end
end

app/controllers/backends/systems_controller.rb
class Backends::SystemsController < BackendsController
  def edit
    render layout: false
  end

  def update
    @system.update(system_params_permit)

    redirect_to :back,flash: { success: '更新成功'}
  end

  def system_params_permit
    params.require(:system).permit(:name, :title, :description, :keyword, :phone,:fax, :address, :email,:facebook)
  end
end

app/controllers/backends_controller.rb
class BackendsController < ApplicationController
  before_action :check_login
  def index

  end

  def destroy
    render json: params
  end

  def check_login
    @admin = Admin.find_by(id: session[:admin_id])
    if @admin.blank?
      redirect_to login_backends_admins_path,flash: { success: '請先登入'}
    end
  end
end

app/helpers/backends/admins_helper.rb
module Backends::AdminsHelper
end

app/helpers/backends/attachments_helper.rb
module Backends::AttachmentsHelper
end

app/helpers/backends/carts_helper.rb
module Backends::CartsHelper
end

app/helpers/backends/categories_helper.rb
module Backends::CategoriesHelper
end

app/helpers/backends/contents_helper.rb
module Backends::ContentsHelper
end

app/helpers/backends/navs_helper.rb
module Backends::NavsHelper
end

app/helpers/backends/orders_helper.rb
module Backends::OrdersHelper
end

app/helpers/backends/products_helper.rb
module Backends::ProductsHelper
end

app/views/backends/navs/_form.html.erb
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label">URL</label>
  <div class="col-lg-9">
    <input type="text" class="form-control" name="nav[url]" value="<%= @nav.url %>" />
  </div>
</div>
<div class="form-group">
  <label class="col-lg-3 col-sm-3 control-label">NAME</label>
  <div class="col-lg-9">
    <input type="text" class="form-control" name="nav[name]" value="<%= @nav.name %>" />
  </div>
</div>
<div class="form-group">
  <div class="col-lg-12">
    <button class="btn btn-block btn-danger">
      確認
    </button>
  </div>
</div>

app/views/backends/navs/edit.html.erb
<%= form_for @nav , :url => {:controller => 'backends/navs', action: :update},:html => {:class => "form-horizontal"} do |b|%>
    <%= token_tag nil %>
    <%= render partial: "/backends/navs/form" %>
  %end%>

app/views/backends/navs/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <nav class="navbar navbar-inverse" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="fa fa-bars"></span>
        </button>
        <a class="navbar-brand" href="#">NAVBAR</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <% if params[:parent_id].present? %>
            <li>
              <%= link_to( 'BACK',backends_navs_path(type: params[:type])) %>
            </li>
            <% end %>
              <li>
                <%= link_to( 'NEW',"#MyModal",data: {action: new_backends_nav_path(type: params[:type],parent_id: params[:parent_id]),title: 'NEW NAV'}) %>
              </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        NAV -
        <%= params[:type] %>
      </header>
      <div class="table-responsive">
        <table class="table table-bordered table-advance table-hover text-center">
          <thead>
            <tr>
              <th class="text-center col-lg-1">#</th>
              <th class="text-center col-lg-3">PARENT</th>
              <th class="text-center col-lg-3">NAME</th>
              <th class="text-center col-lg-3">URL</th>
              <th class="text-center col-lg-1"></th>
            </tr>
          </thead>
          <tbody class="sortable_items" data-url="<%= sort_backends_navs_path %>">
            <% @navs.each do |n| %>
              <tr data-item="<%= n.id %>">
                <td>
                  <%= link_to(backends_navs_path(type: n.nav_type,parent_id: n.id),class: "btn btn-block btn-sm btn-success") do %><i class="fa fa-plus"></i>
                    <% end %>
                      <% link_to("#MyModal",class: "btn btn-block btn-sm btn-success",data: {action: new_backends_nav_path(type: params[:type],parent_id: n.id),title: 'NEW NAV'}) do %><i class="fa fa-plus"></i>
                        <% end %>
                </td>
                <td>
                  <%= n.parent.name if n.parent_id.present? %>
                </td>
                <td>
                  <%= n.name %>
                </td>
                <td>
                  <%= n.url %>
                </td>
                <td>
                  <%= link_to("#MyModal",class: "btn btn-block btn-sm btn-warning",data: {action: edit_backends_nav_path(n),title: 'EDIT NAV'}) do %><i class="fa fa-pencil"></i>
                    <% end %>
                      <%= link_to(backends_nav_path(n),class: "btn btn-block btn-sm btn-danger", method: :delete,data:{confirm: "Are You sure?"}) do %><i class="fa fa-trash-o"></i>
                        <% end %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </section>
  </div>
</div>

app/views/backends/navs/new.html.erb
<%= form_for @nav , :url => {:controller => 'backends/navs'},:html => {:class => "form-horizontal"} do |b|%>
  <%= token_tag nil %>
  <input type="hidden" name="nav[parent_id]" value="<%= params[:parent_id] %>" />
  <input type="hidden" name="nav[nav_type]" value="<%= params[:type] %>" />
  <%= render partial: "/backends/navs/form" %>
<%end%>